# Generated by Django 4.2.7 on 2024-10-07 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_mysite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='apellidos',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='persona',
            name='celular',
            field=models.IntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name='persona',
            name='foto_identificacion',
            field=models.ImageField(default='perfil/iconuser.png', upload_to='perfil/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='genero',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('NB', 'No binario'), ('N/A', 'Prefiero no decirlo')], max_length=3),
        ),
        migrations.AlterField(
            model_name='persona',
            name='nro_documento',
            field=models.IntegerField(max_length=10, unique=True),
        ),
    ]
