# Generated by Django 4.2.7 on 2024-10-07 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_mysite', '0002_alter_persona_apellidos_alter_persona_celular_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='celular',
            field=models.CharField(max_length=10),
        ),
    ]
