# Generated by Django 4.2.7 on 2024-11-26 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('CONSULTAR', 'Consultar'), ('ELIMINAR', 'Eliminar'), ('EDITAR', 'Editar'), ('CREAR', 'Crear')], max_length=10)),
                ('documento', models.CharField(max_length=255)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
