# Generated by Django 4.2.7 on 2024-11-26 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
    ]
